# Generated by Django 4.0.4 on 2022-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMenu', '0002_cita_medica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_medica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
