# Generated by Django 4.0.4 on 2022-05-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='fecha',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
