# Generated by Django 4.0.4 on 2022-05-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_person_alter_game_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Player',
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('foul', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.player')),
            ],
        ),
    ]
